# Generated by Django 5.0.6 on 2024-06-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supplieritem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="supplieritem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_items",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="supplieritem",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_items",
                to="supplier.supplier",
            ),
        ),
    ]
