# Generated by Django 5.0.6 on 2024-06-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_supplieritem_supplier"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="item",
                through="inventory.SupplierItem",
                to="supplier.supplier",
            ),
        ),
    ]
