# Generated by Django 5.0.6 on 2024-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_imageurl_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageurl",
            name="desktop",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imageurl",
            name="mobile",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imageurl",
            name="tablet",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imageurl",
            name="thumbnail",
            field=models.TextField(),
        ),
    ]
